// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.waitme.game.net.protobuf;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Example_protoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Example_proto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string cmd = 1;</code>
     */
    boolean hasCmd();
    /**
     * <code>required string cmd = 1;</code>
     */
    java.lang.String getCmd();
    /**
     * <code>required string cmd = 1;</code>
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>optional int32 keycode = 2;</code>
     */
    boolean hasKeycode();
    /**
     * <code>optional int32 keycode = 2;</code>
     */
    int getKeycode();

    /**
     * <code>optional sint32 posX = 3;</code>
     */
    boolean hasPosX();
    /**
     * <code>optional sint32 posX = 3;</code>
     */
    int getPosX();

    /**
     * <code>optional sint32 posY = 4;</code>
     */
    boolean hasPosY();
    /**
     * <code>optional sint32 posY = 4;</code>
     */
    int getPosY();
  }
  /**
   * Protobuf type {@code Example_proto}
   */
  public static final class Example_proto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Example_proto)
      Example_protoOrBuilder {
    // Use Example_proto.newBuilder() to construct.
    private Example_proto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Example_proto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Example_proto defaultInstance;
    public static Example_proto getDefaultInstance() {
      return defaultInstance;
    }

    public Example_proto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Example_proto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              cmd_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              keycode_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              posX_ = input.readSInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              posY_ = input.readSInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.waitme.game.net.protobuf.Example.internal_static_Example_proto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.waitme.game.net.protobuf.Example.internal_static_Example_proto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.waitme.game.net.protobuf.Example.Example_proto.class, com.waitme.game.net.protobuf.Example.Example_proto.Builder.class);
    }

    public static com.google.protobuf.Parser<Example_proto> PARSER =
        new com.google.protobuf.AbstractParser<Example_proto>() {
      public Example_proto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Example_proto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Example_proto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CMD_FIELD_NUMBER = 1;
    private java.lang.Object cmd_;
    /**
     * <code>required string cmd = 1;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string cmd = 1;</code>
     */
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cmd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cmd = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEYCODE_FIELD_NUMBER = 2;
    private int keycode_;
    /**
     * <code>optional int32 keycode = 2;</code>
     */
    public boolean hasKeycode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 keycode = 2;</code>
     */
    public int getKeycode() {
      return keycode_;
    }

    public static final int POSX_FIELD_NUMBER = 3;
    private int posX_;
    /**
     * <code>optional sint32 posX = 3;</code>
     */
    public boolean hasPosX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional sint32 posX = 3;</code>
     */
    public int getPosX() {
      return posX_;
    }

    public static final int POSY_FIELD_NUMBER = 4;
    private int posY_;
    /**
     * <code>optional sint32 posY = 4;</code>
     */
    public boolean hasPosY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional sint32 posY = 4;</code>
     */
    public int getPosY() {
      return posY_;
    }

    private void initFields() {
      cmd_ = "";
      keycode_ = 0;
      posX_ = 0;
      posY_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCmdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, keycode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, posX_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeSInt32(4, posY_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCmdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, keycode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, posX_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, posY_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.waitme.game.net.protobuf.Example.Example_proto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.waitme.game.net.protobuf.Example.Example_proto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.waitme.game.net.protobuf.Example.Example_proto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.waitme.game.net.protobuf.Example.Example_proto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.waitme.game.net.protobuf.Example.Example_proto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.waitme.game.net.protobuf.Example.Example_proto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.waitme.game.net.protobuf.Example.Example_proto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.waitme.game.net.protobuf.Example.Example_proto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.waitme.game.net.protobuf.Example.Example_proto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.waitme.game.net.protobuf.Example.Example_proto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.waitme.game.net.protobuf.Example.Example_proto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Example_proto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Example_proto)
        com.waitme.game.net.protobuf.Example.Example_protoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.waitme.game.net.protobuf.Example.internal_static_Example_proto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.waitme.game.net.protobuf.Example.internal_static_Example_proto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.waitme.game.net.protobuf.Example.Example_proto.class, com.waitme.game.net.protobuf.Example.Example_proto.Builder.class);
      }

      // Construct using com.waitme.game.net.protobuf.Example.Example_proto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        keycode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        posX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        posY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.waitme.game.net.protobuf.Example.internal_static_Example_proto_descriptor;
      }

      public com.waitme.game.net.protobuf.Example.Example_proto getDefaultInstanceForType() {
        return com.waitme.game.net.protobuf.Example.Example_proto.getDefaultInstance();
      }

      public com.waitme.game.net.protobuf.Example.Example_proto build() {
        com.waitme.game.net.protobuf.Example.Example_proto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.waitme.game.net.protobuf.Example.Example_proto buildPartial() {
        com.waitme.game.net.protobuf.Example.Example_proto result = new com.waitme.game.net.protobuf.Example.Example_proto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.keycode_ = keycode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.posX_ = posX_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.posY_ = posY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.waitme.game.net.protobuf.Example.Example_proto) {
          return mergeFrom((com.waitme.game.net.protobuf.Example.Example_proto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.waitme.game.net.protobuf.Example.Example_proto other) {
        if (other == com.waitme.game.net.protobuf.Example.Example_proto.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          bitField0_ |= 0x00000001;
          cmd_ = other.cmd_;
          onChanged();
        }
        if (other.hasKeycode()) {
          setKeycode(other.getKeycode());
        }
        if (other.hasPosX()) {
          setPosX(other.getPosX());
        }
        if (other.hasPosY()) {
          setPosY(other.getPosY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmd()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.waitme.game.net.protobuf.Example.Example_proto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.waitme.game.net.protobuf.Example.Example_proto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object cmd_ = "";
      /**
       * <code>required string cmd = 1;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string cmd = 1;</code>
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cmd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string cmd = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cmd = 1;</code>
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cmd = 1;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>required string cmd = 1;</code>
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }

      private int keycode_ ;
      /**
       * <code>optional int32 keycode = 2;</code>
       */
      public boolean hasKeycode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 keycode = 2;</code>
       */
      public int getKeycode() {
        return keycode_;
      }
      /**
       * <code>optional int32 keycode = 2;</code>
       */
      public Builder setKeycode(int value) {
        bitField0_ |= 0x00000002;
        keycode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 keycode = 2;</code>
       */
      public Builder clearKeycode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        keycode_ = 0;
        onChanged();
        return this;
      }

      private int posX_ ;
      /**
       * <code>optional sint32 posX = 3;</code>
       */
      public boolean hasPosX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional sint32 posX = 3;</code>
       */
      public int getPosX() {
        return posX_;
      }
      /**
       * <code>optional sint32 posX = 3;</code>
       */
      public Builder setPosX(int value) {
        bitField0_ |= 0x00000004;
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 posX = 3;</code>
       */
      public Builder clearPosX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        posX_ = 0;
        onChanged();
        return this;
      }

      private int posY_ ;
      /**
       * <code>optional sint32 posY = 4;</code>
       */
      public boolean hasPosY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional sint32 posY = 4;</code>
       */
      public int getPosY() {
        return posY_;
      }
      /**
       * <code>optional sint32 posY = 4;</code>
       */
      public Builder setPosY(int value) {
        bitField0_ |= 0x00000008;
        posY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 posY = 4;</code>
       */
      public Builder clearPosY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        posY_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Example_proto)
    }

    static {
      defaultInstance = new Example_proto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Example_proto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Example_proto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Example_proto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\"I\n\rExample_proto\022\013\n\003cmd\030" +
      "\001 \002(\t\022\017\n\007keycode\030\002 \001(\005\022\014\n\004posX\030\003 \001(\021\022\014\n\004" +
      "posY\030\004 \001(\021B\'\n\034com.waitme.game.net.protob" +
      "ufB\007Example"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Example_proto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Example_proto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Example_proto_descriptor,
        new java.lang.String[] { "Cmd", "Keycode", "PosX", "PosY", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
